### ISSUE TITLE
connect to mysql

### ISSUE THREAD

**Issue by Yaozu-Xu** [solodyagin/docker-compose-wamp#2]
I wanted to connect mysql using mysqli, i got an erro Failed to connect to MySQL: Connection refused. But i don't know how to fix it. Could you give me some help ? Thanks in advance !

my code:

$mysqli = new mysqli("127.0.0.1","root", "tiger");

// Check connection
if ($mysqli -> connect_errno) {
  echo "Failed to connect to MySQL: " . $mysqli -> connect_error;
  exit();
}

**Comment by aymhenry** [comment]
- Run phpMyAdmin
- Check IP for your mySQL
- put that IP instead of local host addresd.

**Comment by Yaozu-Xu** [comment]
Thanks aymhenry, it works.
